apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: busybox-multi-pod
  name: busybox-multi-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      run: busybox-multi-pod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: busybox-multi-pod
    spec:
      containers:
      - image: busybox
        imagePullPolicy: Always
        command: ["/bin/sh","-c","sleep 1000"]
        name: busybox-1
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      - image: busybox
        imagePullPolicy: Always
        command: ["/bin/sh","-c","sleep 1000"]
        name: busybox-2
        resources:
          requests:
            memory: "1Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"


