version: '3.8'
services:

  postgresql:
    image: postgres:15-alpine
    container_name: postgresql
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=appdb
    ports:
      - "5432:5432"
    networks:
      - order-network

  zipkin-server:
    image: openzipkin/zipkin
    container_name: zipkin-server
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    deploy:
      resources:
        limits:
          memory: 512m
    expose:
      - "9411"
    ports:
      - "9411:9411"
    networks:
      - order-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.3
    container_name: zookeeper
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: [ "CMD-SHELL", "echo ruok | nc localhost 2181" ]
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - "22181:2181"
    networks:
      - order-network

  kafka:
    image: confluentinc/cp-kafka:7.3.3
    container_name: kafka
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 9092" ]
      interval: 30s
      timeout: 5s
      retries: 3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - order-network

  config-server:
    container_name: config-server
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    image: dockertmt/mmv2-config-server-17:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "8888:8888"
    depends_on:
      - zookeeper
    networks:
      - order-network
    environment:
      SPRING_PROFILES_ACTIVE: native

  naming-server:
    container_name: naming-server
    image: dockertmt/mmv2-service-registry-17:0.0.1-SNAPSHOT
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "8761:8761"
    networks:
      - order-network
    depends_on:
      config-server:
        condition: service_started
    environment:
      - SPRING.ZIPKIN.BASEURL= http://zipkin-server:9411/
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888/
    restart: unless-stopped

  inventory-service:
    container_name: inventory-service
    image: dockertmt/mmv2-inventory-service:0.0.1-SNAPSHOT
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "18081:18081"
    networks:
      - order-network
    depends_on:
      kafka:
        condition: service_healthy
      naming-server:
        condition: service_started
      postgresql:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE= docker
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888/
      - EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE=http://naming-server:8761/eureka
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:29092
    restart: unless-stopped

  catalog-service:
    container_name: catalog-service
    image: dockertmt/mmv2-catalog-service:0.0.1-SNAPSHOT
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "18080:18080"
    networks:
      - order-network
    depends_on:
      kafka:
        condition: service_healthy
      naming-server:
        condition: service_started
      postgresql:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE= docker
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8888/
      - EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE=http://naming-server:8761/eureka
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:29092
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin-server:9411/api/v2/spans
    restart: unless-stopped

networks:
  order-network:


volumes:
  postgres_data:
    driver: local
