spring.application.name: order-query-service

spring.kafka.bootstrap-servers: pminkows-k-c-ma--adc-smj-himh-g.bf2.kafka.rhcloud.com:443

spring.cloud.stream.bindings.orders-in-0.destination: user.pminkows.ordercommand
spring.cloud.stream.kafka.bindings.orders-in-0.consumer.startOffset: earliest
spring.cloud.stream.kafka.bindings.orders-in-0.consumer.resetOffsets: true

spring.cloud.stream.bindings.confirmations-in-0.destination: user.pminkows.confirmcommand
spring.cloud.stream.kafka.bindings.confirmations-in-0.consumer.startOffset: earliest
spring.cloud.stream.kafka.bindings.confirmations-in-0.consumer.resetOffsets: true

spring.cloud.stream.bindings.queries-in-0.destination: user.pminkows.orderquery
spring.cloud.stream.bindings.queries-in-0.consumer.maxAttempts: 5

spring.cloud.stream.bindings.queries-out-0.destination: user.pminkows.orderqueryresult

spring.cloud.function.definition: orders;confirmations;queries

#spring.cloud.stream.kafka.streams.binder.configuration.security.protocol: SASL_SSL
#spring.cloud.stream.kafka.streams.binder.configuration.sasl.mechanism: PLAIN
#spring.cloud.stream.kafka.streams.binder.configuration.sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="srvc-acct-7e2b5429-257e-4b32-a0a7-593d20310267" password="25f07668-33d8-494b-9791-10acbc485b7f";

spring.cloud.stream.kafka.binder.configuration.security.protocol: SASL_SSL
spring.cloud.stream.kafka.binder.configuration.sasl.mechanism: PLAIN
spring.cloud.stream.kafka.binder.jaas.loginModule: org.apache.kafka.common.security.plain.PlainLoginModule
spring.cloud.stream.kafka.binder.jaas.options.username: srvc-acct-7e2b5429-257e-4b32-a0a7-593d20310267
spring.cloud.stream.kafka.binder.jaas.options.password: 25f07668-33d8-494b-9791-10acbc485b7f