name: Build Delivery Service Micronaut

on:
  push:
    paths:
      - delivery-service-micronaut/**
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./delivery-service-micronaut
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/delivery-service-micronaut
      DOCKER_NATIVE_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/delivery-service-micronaut-native
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw verify

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build and Publish Docker Image
        run: |
          ./mvnw package -Dpackaging=docker
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push $DOCKER_IMAGE_NAME
