kind: Service
apiVersion: v1
metadata:
  name: springboot-postgres-k8s
  labels:
    name: springboot-postgres-k8s
spec:
  ports:
    - nodePort: 30163
      port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    app: springboot-postgres-k8s
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-postgres-k8s
spec:
  selector:
    matchLabels:
      app: springboot-postgres-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-postgres-k8s
    spec:
      containers:
        - name: springboot-postgres-k8s
          image: mertcakmak2/springboot-postgres-k8s
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8082
#          env:
#            - name: DB_HOST
#              valueFrom:
#                configMapKeyRef:
#                  name: postgres-conf
#                  key: host
#            - name: DB_NAME
#              valueFrom:
#                configMapKeyRef:
#                  name: postgres-conf
#                  key: name
#            - name: POSTGRES_USER
#              valueFrom:
#                secretKeyRef:
#                  name: postgres-credentials
#                  key: postgres_user
#            - name: POSTGRES_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: postgres-credentials
#                  key: postgres_password