version: '3'
services:

    redis:
        image: redis:6.0.9
        ports:
            - "6379:6379"
        environment:
            - REDIS_REPLICATION_MODE=master
        restart: unless-stopped

    redis-commander:
        container_name: redis-commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: always
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - "9081:8081"
