apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization
  labels:
    app: organization
    app.openshift.io/runtime: spring-boot
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: organization-app
  annotations:
    app.openshift.io/connects-to: organization-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: organization
  template:
    metadata:
      labels:
        app: organization
        app.openshift.io/runtime: spring-boot
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: organization-app
      annotations:
        app.openshift.io/connects-to: organization-db
    spec:
      containers:
        - name: organization
          image: piomin/organization
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: organization-db
                  key: database-name
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: organization-db
                  key: database-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: organization-db
                  key: database-password
---
apiVersion: v1
kind: Service
metadata:
  name: organization
  labels:
    app: organization
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: organization