version: "3.7"
services:
#  nginx:
#    image: nginx:1.15-alpine
#    container_name: nginx
#    restart: always
#    links:
#      - springapp
#    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:Z
#    ports:
#      - 80:80
  db:
    container_name: user-postgre
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: userdatabase
    # expose:
    #   - "5433"
    ports:
      - "5433:5433"
#  pgadmin:
#    container_name: user-pgadmin4
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - "5051:80"
  redis:
    container_name: redis
    image: redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_vol:/var/lib/redis/data
  springapp:
    container_name: springapp
    build: .
    ports:
      - "5005:5005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/userdatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      DB_HOST: db
    depends_on:
      - db

volumes:
  redis_vol:
