application:
  audience: ${env.AUTH0_AUDIENCE:}
  client-origin-url: ${env.CLIENT_ORIGIN_URL:}

server:
  port: ${env.PORT:0}
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${env.AUTH0_DOMAIN}/
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  redis:
    host: localhost
    port: 6379
    time-to-live: 6000