apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee
  labels:
    app: employee
    app.openshift.io/runtime: spring-boot
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: employee-app
  annotations:
    app.openshift.io/connects-to: employee-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee
  template:
    metadata:
      labels:
        app: employee
        app.openshift.io/runtime: spring-boot
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: employee-app
      annotations:
        app.openshift.io/connects-to: employee-db
    spec:
      containers:
        - name: employee
          image: piomin/employee
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: employee-db
                  key: database-name
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: employee-db
                  key: database-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: employee-db
                  key: database-password
---
apiVersion: v1
kind: Service
metadata:
  name: employee
  labels:
    app: employee
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: employee