version: "3.8"
services:
  bookstore-ui:
    container_name: bookstore-ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      PRODUCT_SERVICE_API_BASE_URL: http://localhost:8081
      ORDER_SERVICE_API_BASE_URL: http://localhost:8082
