apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: microservices-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - quarkus-insurance-app.apps.cluster-5935.5935.sandbox474.opentlc.com
        - quarkus-person-app.apps.cluster-5935.5935.sandbox474.opentlc.com