apiVersion: v1
kind: Service
metadata:
  name: quarkus-person-app
  labels:
    app: quarkus-person-app
spec:
  type: ClusterIP
  selector:
    app: quarkus-person-app
  ports:
  - port: 8080
    name: http
