spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testing
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true 
    database: postgresql
  redis:
    host: localhost
    port: 6379
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 8
  cache:
    type: redis
    redis:
      time-to-live: 30
      cache-null-values: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub
server:
  port: 8080
clear:
  all:
    cache:
      fixed:
        rate: 

management:
  endpoints:
    web:
      exposure:
        exclude: "*"
                  
  endpoint:
    shutdown:
      enabled: true