spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app.client.url: http://localhost:4200/login

redis:
  host: localhost
  port: 6379

application:
  jwtAccessCookieName: ryCoding-jwt-access
  jwtRefreshCookieName: ryCoding-jwt-refresh
  jwt:
    secretKey: super-secret
    expiration: 86400000 # a day
    refreshToken:
      expiration: 604800000 # 7 days