name: order-service

on:
  push:
    paths:
      - "order-service/**"
    branches: [master]
  pull_request:
    paths:
      - "order-service/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    name: Order Service with jdk  ${{ matrix.java }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "order-service"
    strategy:
      matrix:
        java: ["17"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis

      - uses: graalvm/setup-graalvm@v1
        with:
          version: "latest"
          java-version: ${{ matrix.java }}
          components: "native-image"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: "maven"

      - name: Printing versions
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          gu --version
          native-image --version

      - name: Build, analyze & Sonar Scan
        if: ${{ github.ref == 'refs/heads/master' }}
        run: ./mvnw clean verify sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and analyze non master
        if: ${{ github.ref != 'refs/heads/master' }}
        run: ./mvnw clean verify

      - if: ${{ github.ref == 'refs/heads/master' }}
        name: Build Image and push to docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          DOCKER_PASSCODE: ${{secrets.DOCKER_PASSCODE}}
        run: ./mvnw spring-boot:build-image -DskipTests -DCI_DOCKER_PASSWORD=${DOCKER_PASSCODE} -DCI_DOCKER_USERNAME=dockertmt -Dspring-boot.build-image.publish=true
