version: "3.8"
services:

  bookstore-postgres:
    image: postgres:15-alpine
    container_name: bookstore-postgres
    environment:
      - POSTGRES_MULTIPLE_DATABASES=products,orders
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./create-schemas.sh:/docker-entrypoint-initdb.d/create-schemas.sh
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.11.5-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"