version: '3.9'
services:
  redis:
    image: "redis/redis-stack:latest"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure


  insight:
    image: "redislabs/redisinsight:latest"
    container_name: insight
    ports:
      - "8001:8001"
    volumes:
      - ./redisinsight:/db
    depends_on:
      - redis
