apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-rolling-app
  name: nginx-rolling-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-rolling-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-rolling-app
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"


