name: Dev Branch CI

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3.1.0
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvn clean install
