apiVersion: v1
kind: Service
metadata:
  name: simple-counter
spec:
  type: ClusterIP
  selector:
    app: simple-counter
  ports:
  - port: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-counter
  template:
    metadata:
      labels:
        app: simple-counter
    spec:
      containers:
      - name: simple-counter
        image: piomin/simple-counter
        ports:
          - containerPort: 8080
        env:
          - name: DIVIDER
            value: '3'
