service: backup-db

frameworkVersion: '2'

provider:
  name: aws
  region: eu-west-3
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ecr:InitiateLayerUpload"
            - "ecr:SetRepositoryPolicy"
            - "ecr:GetRepositoryPolicy"
          Resource: [ "arn:aws:ecr:eu-west-3:401324569655:repository/*" ]

functions:
  backup-db:
    image: 401324569655.dkr.ecr.eu-west-3.amazonaws.com/backup-db@sha256:14329d01b69cac0795734f907575557ccae0df90c79a7f3be88f3292675411b5
    timeout: 900
    events:
      - schedule: cron(15 7 * * ? *)